### PR TITLE
Feature/support markdown

### LINKED ISSUE #615: Support rich text
**Is your feature request related to a problem? Please describe.**
People want to have better descriptions for everything, and #601 already helps with that. Now that we have more characters to play with, the next step is supporting some form of rich text.

**Describe the solution you'd like**
We need two things:
- A way to render rich text (it should follow our design system). This would mean parsing the rich text into HTML which should be easy to style as we wish.
- A way to edit rich text. We should probably have some WYSIWYG editor like Slack or Reddit. It can be very simple, as far as it allows for showing the formatted text as it's being edited.

**Describe alternatives you've considered**
The simplest form of rich text is probably markdown. If we go with that:
- We have a few Elm packages for rendering it. One that catches attention is [dillonkearns/elm-markdown](https://package.elm-lang.org/packages/dillonkearns/elm-markdown/latest/). The generated HTML is completely customizable, and it's made by Dillon Kearns :sunglasses: .
- We could use custom elements for the editor. Something like [simplemde](https://simplemde.com/) would probably do the trick.

**Additional context**
Markdown was suggested by @lucca65 when talking about the new shop design

### PR DESCRIPTION
**Pull request by NeoVier**
## What issue does this PR close
Closes #615, #591

## Changes Proposed ( a list of new changes introduced by this PR)
- Add [QuillJS](https://quilljs.com/) as a custom element for our markdown editor.
- Add [dillonkearns/elm-markdown](https://package.elm-lang.org/packages/dillonkearns/elm-markdown/latest/) to parse and display markdown from the server.
- Remove max length on transfer/shop memos and profile bios.
- Add a new `LoggedIn.BroadcastMsg`, so we know when translations have loaded.
- Use the new markdown editor in pages affected by #601 and the ones listed in #591. Here are all the areas of the app affected (all of them have an editing screen and (at least) a viewing screen, so test all of the screens these items show up!): 
  - Action photo proof instructions
    - Claiming action
    - Editing action
  - Action description
    - Claim card
    - Claim modal
    - Claim page
    - Editing action
    - Claiming action
    - "How to earn" page
  - Community description
    - Editing community info
    - New community page
    - "How to earn" page
    - Join page
  - Objective description
    - "How to earn" page
    - Objective editor
    - Claim page
  - Transfer memo
    - "Transfer to a friend" page
    - Dashboard
    - Private profile (transfer list)
    - Transfer page
  - Shop memo
    - "Buy product" page
  - Product description
    - "Create offer" page
    - Product page
  - Profile Bio
    - Edit profile page
    - Public/private profile page

## How to test ( a list of instructions on how to test this PR)
1. Be logged in as an admin
2. Check out if you can edit and view rich text on the pages listed above

**Note**: this PR removes the maximum length on transfer/shop memos and profile bios (check out [this Slack thread](https://cambiatus.slack.com/archives/CA83HJAAD/p1629234643009000)), but as of this writing, those changes haven't been applied to the backend/blockchain, so you might get some chopped strings if you try to input more than 255 characters on those fields, but they should go back to normal as soon as those restrictions are removed from the backend.

### CODE REVIEW

**Comment by NeoVier** [comment]
> Figure out how to integrate with the backend

@lucca65 As most other components I found, QuillJS uses their own representation, in the format of a JSON object, like this:

```js
[
  { insert: 'Hello', { bold: true } },
  { insert: '\n', { align: 'center' } },
  { insert: { formula: 'x^2' } },
  { insert: '\n', { align: 'center' } },
  { insert: 'World', { italic: true }},
  { insert: '\n', { align: 'center' } }
]
```

It's probably pretty easy to translate to/from markdown, but it would be even easier if we could store it as is :sweat_smile:. Do you think it's better to store it as a plain `String` that we can convert back to this format? Would it even be possible to store it like that, since we use blockchain?

**Comment by lucca65** [comment]
It is! My main concern is XSS, as this will be fed to a script a browser later on.

The alternatives would be to store it as a JSON element, so we get some kind of validation, but idk, since the backend won't do much with it, only display it back... 

You can try with the normal string method with the current code we have on the backend!

**Review by lucca65 — DISMISSED** [review]
damn, this looks fire!!! absolutely amazing! love the fact I can `cmd+K` to create links! 

Is it possible for us to activate the ability to add headers?

**Comment by NeoVier** [comment]
For sure, it's definitely possible! I'll work on that :mechanic:

**Comment by NeoVier** [comment]
There you go @lucca65. We have the option to have a dropdown/modal to select more heading levels (up to h6), but I opted to have 2 separate buttons for h1 and h2. IMO 2 heading levels (which is what Quill makes available as separate buttons) are enough, and the separate buttons make for a better UX and cleaner UI (also, looking at other editors like Reddit, GitHub and Slack, they usually provide from 0 to 2 options as well)

**Comment by lucca65** [comment]
+1 I think it is enough to have the two options! Shop descriptions will look even better!

**Review by lucca65 — APPROVED** [review]
✨ 🏠

**Review by lucca65 — APPROVED** [review]
renewing approval...

**Comment by juramos-2020** [comment]
@NeoVier 

sorry for the delay, i will be checking the design now

**Comment by juramos-2020** [comment]
**- Descrição da ação** - ok working 👌

**- Descrição da comunidade**
Editando informações da comunidade - ok working 👌
Página "Como ganhar" - ok working 👌
Nova página da comunidade -  Qual seria a tela? ⚠
Página de adesão -  Qual seria a tela? ⚠


- **Transferir memorando** 
Página de sucesso da transferencia ⚠
O itálico não está funcionando corretamente.
memorando


Perfil privado (lista de transferência) ⚠
A página está com scroll na horizontal. 
perfil
perfil 1



**- Instruções à prova de foto de ação**⚠
O negrito não está funcionando corretamente.
ação com prova de foto



**- Objective description ⚠**
O negrito não está funcionando corretamente. Deveria estar negrito e não estar aparecendo o ***

objetivo 1
objetivo
objetivo 2




Cont...

**Comment by juramos-2020** [comment]
**Shop memo**
"Buy product" page

- 


**Product description**
"Create offer" page - - ok working 👌
Product page - - ok working 👌
Product Purchase Detail - Transfer List - - ok working 👌 (I added this step)

**Profile Bio**
Edit profile page - the rich text it's working, but the screen is scrolling horizontally

perfil edição


Public/private profile page - the same error listed above


"Editing the offer" ⚠
Por algum motivo ao clicar na seta para quebrar a linha (enter) a oferta é salva.

**Comment by lucca65** [comment]
Those are the cutest test results I've ever seem @juramos-2020 😍

**Comment by juramos-2020** [comment]
Hahahahaha 😂✌️

**Comment by NeoVier** [comment]
Obrigado pelo feedback @juramos-2020!!

> Nova página da comunidade - Qual seria a tela? :warning:

Não temos como entrar nessa tela diretamente, mas o link é `/community/new`.

> Página de adesão - Qual seria a tela? :warning:

É uma página mostrada somente para usuários não logados. O link dela é `/join`, e ela aparece quando o usuário não está logado e entra no link da comunidade.


Quanto aos outros erros, me parecem simples de corrigir. Logo volto com novidades :mechanic:

**Comment by NeoVier** [comment]
@juramos-2020 aparentemente tudo foi consertado... Lembrando que vai ter que editar os textos (ou criar novos) para que algumas correções tomem efeito

**Comment by juramos-2020** [comment]
**Action photo proof instructions** ok working 👌
**Action description** - ok working 👌
**Community description** ok working 👌
**Objective description** ok working 👌

**Transfer memo**
Tem restrição de caractere nessa página? Fiz um teste com uma mensagem grande e disse:
"a mensagem não pode ter mais que 256 carácteres"
Depois eu diminui os caracteres e deu tudo certo - ok working 👌

Dashboard  - ok working 👌
Private profile (transfer list)  - ok working 👌
Transfer page  - ok working 👌

**Shop memo**
**Product description** ok working 👌
**Profile Bio** - ok working 👌


**Join page**  - Não aparece a descrição da comunidade. Porém no perfil da comunidade ("How to earn" page) aparece e está tudo certo.
image



**New community page** - estou usando o caminho que você me indicou mas acho que estou fazendo algo de errado 😅 
Não tenho certeza se é essa a página que deveria testar.... 
Se for, a descrição do objetivo não está aparecendo nela.
Pelo o que entendi o link do convite ta direcionando para entrar na comunidade da Cambiatus ao invés da Nomad. E deve ser por isso que a descrição do objetivo não esteja aparecendo.
image

**Comment by NeoVier** [comment]
> Tem restrição de caractere nessa página?

No momento sim... Mas o @lucca65 vai tirar isso, podemos ignorar esse erro por ora

> Não aparece a descrição da comunidade.

Essa é a página de invite... A página de join é essa segunda que vc mandou :sweat_smile:. O problema é que nesse nosso link, ele manda sempre pra comunidade Cambiatus.

> estou usando o caminho que você me indicou mas acho que estou fazendo algo de errado

De novo por causa do ambiente... Já enviei uma proposta para arrumar isso (#628), mas ainda não foi aprovada. De qualquer forma, essas duas páginas são bem simples e usam o mesmo componente que as outras, então com certeza estão de acordo também :smile:

**Pull request merged**
