### PR TITLE
Feature/user search

### LINKED ISSUE #600: Tool for checking user balance
**Is your feature request related to a problem? Please describe.**
There is no way for community admins to check the "events" on a community. We could have a screen where it's possible to search a user and get a bunch of information related to him/she.

**Describe the solution you'd like**
- Show balance
- Show transfers
- Show Claims
- Link to block explorer

### PR DESCRIPTION
**Pull request by NeoVier**
## What issue does this PR close
Closes #600 

## Changes Proposed ( a list of new changes introduced by this PR)
- Use a single route/module to represent public and private profiles. This way it's far easier to understand what's going on, and we don't need to duplicate code for queries and etc. We also don't need to check if we should redirect to the public or private profile page if the profile is the logged user or not.
- Add ability to search for users.
- Show more data about the user (if the one looking is either the admin or the user themselves): total balance, last transaction date, shop offers, etc.

## How to test ( a list of instructions on how to test this PR)
1. Use the search bar to search for a user. It should show products, actions and users.
2. Go to a user's profile from the search page. If you're not the admin or the user, you should see the same thing as usual. If you're the admin or the user, you should see some more info on the right side, such as total balance and the last transfers the user sent/received.

### CODE REVIEW

**Review by lucca65 — DISMISSED** [review]
🔥 

Damn bro this looks fine AF!

Love the way it looks when I'm a community admin, really beautiful

Thanks so much for the hard work! I'm really happy about it 💪

**Comment by juramos-2020** [comment]
Hi folks

is having a page break

**Comment by juramos-2020** [comment]
I'm trying to upload the video to show this break but I'm not getting it

**Comment by NeoVier** [comment]
Uh.. looks like you're trying to view it as a dekstop site maybe? It's hard to tell from that screenshot. If you're having trouble sending the video here, you can send it on the #devs channel on Slack

**Comment by NeoVier** [comment]
@juramos-2020 I've identified the bug, I'm working on it! :bug: :hammer:

**Comment by NeoVier** [comment]
@lucca65 @juramos-2020 that was probably the most obscure CSS bug ever, but it should hopefully be fixed now :pray:  can you test again please?

**Review by lucca65 — APPROVED** [review]
✨

**Comment by NeoVier** [comment]
ping @juramos-2020 can you check if that issue still happens?

**Comment by juramos-2020** [comment]
Is working perfectly 😍

**Comment by juramos-2020** [comment]
I don't know if we could solve this issue but I think it would be a case of creating a new improvement.  When typing in the search options/suggestions do not appear immediately.  They only appear if we stay in "go" of the keyboard.

**Comment by juramos-2020** [comment]
What do you think about this?

**Comment by NeoVier** [comment]
I agree 1000000%! But yeah, we should definitely do this in another issue

**Pull request merged**
