### PR TITLE
Feature/contact

### LINKED ISSUE #472: Adds contact information to the public profile
We need to make sure that we only display if the loggedIn user belongs to any of the public profile user communities.

Also extend this logic to KYC information that is displayed on the public profile too.

https://www.figma.com/file/ILiFX32kN5TRQtUhbA0Z5u/New-Shop?node-id=13%3A4356

### LINKED ISSUE #473: Create "Add a Phone Number" Modal
This modal has several rules, about when it should appear, including a "New Tag" and some local storage information. 

Users will always be prompted as long as they 

1) don't fill in their phone
2) havent explicitly asked not to see the modal again

https://www.figma.com/file/ILiFX32kN5TRQtUhbA0Z5u/New-Shop?node-id=4%3A408

### LINKED ISSUE #474: Update contact information on the Private Profile

### PR DESCRIPTION
**Pull request by NeoVier**
## What issue does this PR close
Closes #473, closes #474 and closes #472 

## Changes Proposed ( a list of new changes introduced by this PR)
- Add a modal that asks the user to add a contact information if they don't have any
- Update the public profile with the new design, and add the ability to see the user's contacts
- Update the private profile with the new design, and add the ability to add/edit own contacts

## How to test ( a list of instructions on how to test this PR)
Log into an account that has no contact and see if the modal shows up. Try adding a contact. If the user already has a contact, this shouldn't show up
Go into your private profile and try adding/deleting contacts
Go into someone's public profile and look at their contacts. Test the links to see if they open correctly

### CODE REVIEW

**Review by lucca65 — DISMISSED** [review]
nice! :shipit:

**Comment by NeoVier** [comment]
@heltonlr Can you test this on staging please? It includes the modal you've already tested, and the public/private profile redesign.

The modal is only shown if the user doesn't have any contacts added, and it's set to not show up anymore after 01/01/2022. Is that date fine or should we change it?

@lucca65 The Netlify deploys aren't working with the auth update, it sends an empty password. I'm not sure how it's set up, but maybe we need to define the `GRAPHQL_SECRET` environment variable on Netlify?

**Comment by lucca65** [comment]
@NeoVier yeah, I don't know how to do it on netlify actually we need to dig deeper on to this

**Comment by heltonlr** [comment]
> @heltonlr Can you test this on staging please? It includes the modal you've already tested, and the public/private profile redesign.
> 
> The modal is only shown if the user doesn't have any contacts added, and it's set to not show up anymore after 01/01/2022. Is that date fine or should we change it?
> 
> @lucca65 The Netlify deploys aren't working with the auth update, it sends an empty password. I'm not sure how it's set up, but maybe we need to define the `GRAPHQL_SECRET` environment variable on Netlify?

Sure, I will finish tomorrow and let you know!!

**Review by lucca65 — APPROVED** [review]

**Comment by NeoVier** [comment]
@heltonlr Everything should be fixed now

@lucca65 Should I merge this or do you want to wait for after the auth update? Or should this also include #497?

**Comment by lucca65** [comment]
we can address #497 right after it! merge on! this deploy will include more stuff 💪

**Comment by heltonlr** [comment]
> @heltonlr Everything should be fixed now
> 
> @lucca65 Should I merge this or do you want to wait for after the auth update? Or should this also include #497?

Thanks, @NeoVier , awesome job

**Pull request merged**
