### PR TITLE
Enhancement/keyboard enter

### LINKED ISSUE #100: Forms should works with enter (keyboard)
**Describe the bug**
Forms do not send the data when user click enter on the keyboard.

**To Reproduce**
1. Go to any form
2. Enter the data
3. Click enter on the keyboard

**Expected behavior**
- When user click enter on the keyboard , send the data.

**Screenshots**
--

**Cambiatus Env you are using**
- muda.cambiatus.io

**Desktop (please complete the following information):**
 - not apply

**Smartphone (please complete the following information):**
 - Device: Samsung (several) and Xiaomi;
 - OS: Android;
 - Browser: Chrome;
 - Version: --

**Additional context**
--

### PR DESCRIPTION
**Pull request by Pancakem**
## What issue does this PR close
Closes #100 

## Changes Proposed ( a list of new changes introduced by this PR)
A enter keystroke should submit a form

### CODE REVIEW

**Comment by Pancakem** [comment]
Hey @lucca65. I apologize for taking so long with this issue. I am working on getting it closed as soon as possible. I have a few concerns on how to go about it.

**Comment by zacck** [comment]
Hey @Pancakem  what concerns do you have?

**Comment by Pancakem** [comment]
> Hey @Pancakem what concerns do you have?

For example, at this line https://github.com/Pancakem/frontend/blob/enhancement/keyboard-enter/src/elm/Page/Community/Editor.elm#L796 I get the enter keystroke msg but I don't want to repeat the code at https://github.com/Pancakem/frontend/blob/enhancement/keyboard-enter/src/elm/Page/Community/Editor.elm#L678 to submit the form. I have tried to look for a way to trigger `ClickedSave` from `PressedEnter` with no success.

**Comment by zacck** [comment]
You can trigger it as it is triggered here https://github.com/Pancakem/frontend/blob/b3aeecd6af17cfd7b077cf36c2aae8c1b63c109b/src/elm/Page/Community/Editor.elm#L683 @Pancakem

**Comment by Pancakem** [comment]
> You can trigger it as it is triggered here https://github.com/Pancakem/frontend/blob/b3aeecd6af17cfd7b077cf36c2aae8c1b63c109b/src/elm/Page/Community/Editor.elm#L683 @Pancakem

Wow. That is part of the UpdateResult library? 😮  Cool. Thanks @zacck

**Comment by zacck** [comment]
@Pancakem  can we get you unstuck?

**Comment by Pancakem** [comment]
> @Pancakem can we get you unstuck?

I have it working in all of the listed pages, except the login page.

**Comment by Pancakem** [comment]
Hey @zacck looks like I am done.

**Comment by zacck** [comment]
@Pancakem  could you please rebase this on `master` so we we can move on with the review and merging?

**Comment by Pancakem** [comment]
Hey @zacck after rebasing I get this: 
image

**Comment by Pancakem** [comment]
@Lucca I figured something was terribly wrong with the merging. That's a great blog, I loved it. Though I have decided to re-do it.

**Pull request closed without merging**
