### PR TITLE
Allow edit of invited_reward and inviter_reward

### LINKED ISSUE #66: Allow edit of invited_reward and inviter_reward
Right now on the Community Editor page we have a few fields that allow changing the name, description and logo of a community. We need to add two more fields to it. `invited_reward` and `inviter_reward`. Those fields are currently hard coded in the function that pushes the edit action to the blockchain. We just need to hook those input values into the ports call to edit the community

### PR DESCRIPTION
**Pull request by Pancakem**
Fixes #66

### CODE REVIEW

**Comment by Pancakem** [comment]
@zacck tooltips for the new fields need translations.

**Comment by zacck** [comment]
@Pancakem  what phrases do you need translated you can paste them here and I can add them to your PR

**Comment by lucca65** [comment]
@Pancakem Thanks **SO MUCH** for your contribution. I'm so happy to have help on those stuff!

@zacck I have a few changes to do on this PR, the transaction isn't being updated. I'll commit here directly.

**Comment by zacck** [comment]
@lucca65  yes you can do that so that @Pancakem  can see how it all ties up into the contracts

**Comment by Pancakem** [comment]
@zacck `community.create.tooltips.invited_reward` and `community.create.tooltips.inviter_reward` these need translations.

**Comment by lucca65** [comment]
those phrases aren’t defined @zacck. we have to come up with new ones

**Comment by zacck** [comment]
@Pancakem  do you have the actual phrases you want to use in the tooltips, some sort of explanation perhaps?

**Comment by Pancakem** [comment]
@zacck I guess it should be like this `"description": "Tell us about your community and what problem it is facing."`. An instruction on what the user should enter.

**Comment by zacck** [comment]
Hey @Pancakem so maybe use this inviter reward `This is the amount of tokens on receives for inviting another user` invited reward `This is the amount of token a user receives when they join the system`

With this these now you can use google translate to find the translations for 
- catalan 
- portuguese 
- spanish 

Then you will need to add this keys 
`community.create.tooltips.invited_reward` and `community.create.tooltips.inviter_reward`

to the translations files at 

`public/translations`

specifically you would have to add them to the community object here 
https://github.com/cambiatus/frontend/blob/5b44868aad36f186b8178b95ee39d8dd0a425ab8/public/translations/en-US.json#L206

**Comment by zacck** [comment]
@Pancakem  nice one!

**Comment by lucca65** [comment]
@zacck can you deploy this to cambiatus?

**Comment by zacck** [comment]
@lucca65  doing so now

**Pull request merged**
