### PR TITLE
Enhancement/pdf upload

### LINKED ISSUE #541: Allow PDF upload on mobile
**Is your feature request related to a problem? Please describe.**
When uploading a file as evidence for a claim, its not possible to select a PDF on mobile

**Describe the solution you'd like**
File selector should allow me to select a PDF

**Describe alternatives you've considered**
None

**Additional context**
Tested on demo after the newest multidomain version

### PR DESCRIPTION
**Pull request by NeoVier**
## What issue does this PR close
Closes #541 

## Changes Proposed ( a list of new changes introduced by this PR)
- Add pdf as a file upload option
- Add ability to display thumbnail of pdf
- Add pdf as an option for claims

## How to test ( a list of instructions on how to test this PR)
- Try to claim an action that requires photo proof
- See if you can choose to upload a pdf as well as an image
- Try uploading an image and see if it still works (should be uploaded and shown on the preview)
- Try uploading a `.pdf` file and see if it works as well (should be uploaded and shown on the preview)
- Go to your claims and see if you can see a preview of the pdf file on the claim card
- Open the claim and see if you can see a preview of the pdf on the claim page/modal

### CODE REVIEW

**Review by lucca65 — CHANGES_REQUESTED** [review]
I've found some stuff...

1. I know its not related to exactly this but I found some visual glitches on the action form (i'll send you the image on slack, I'm without my computer)
2. The texts should show "photo/pdf" or something similar, i've found references on the make claim page on the community page (how i wish it was a modal bro), action form and the view claim
3. After uploading an pdf, we could have the loader until the process to show the pdf is done. 
4. After uploading a PDF, I can still see a modal just before being redirected to the dashboard

Do you think we can fix those on this PR, I think it makes sense

**Comment by NeoVier** [comment]
> I know its not related to exactly this but I found some visual glitches on the action form (i'll send you the image on slack, I'm without my computer)

I noticed the input label on #553, and fixed it there, so it should be gone when I merge this with master. I'll take a look at the highlighting of the currency input

> The texts should show "photo/pdf" or something similar, i've found references on the make claim page on the community page (how i wish it was a modal bro), action form and the view claim

Makes sense! Do you think we should also change the camera icon on the file uploader?

+1 on the other points, I'll fix them as well. I do think it makes sense to fix them in this PR

**Review by lucca65 — COMMENTED** [review]
can we do the same (showing the loading) on the claim card/page, before the file loads?

**Review by lucca65 — CHANGES_REQUESTED** [review]
It looks awesome! so nice to see the mini loading gifs all over the claims!! 

one small note: it looks like this after a while, maybe the request is falling but we are not displaying it correctly... idk really! you can log with `Lucca` account and go to MIZU to check this error
Captura de Tela 2021-06-07 às 15 53 01

**Comment by NeoVier** [comment]
Oh, that's weird :thinking:. Is this happening on a specific claim or in any of them? It's working correctly for me in all of the ones from mizu

**Comment by lucca65** [comment]
on two specific ones, looks like at some point the PDF upload failed somehow, in any way this might happen again, it would be nice to have someway to display failed PDF loadings

**Comment by lucca65** [comment]
because the user can still click to see the file directly

**Comment by NeoVier** [comment]
Agreed, we could have it timeout and show a default image saying the pdf failed loading. What image should we use?

**Comment by lucca65** [comment]
maybe the one we use for 404, of the broken car? i think it fits the theme well enough

**Comment by NeoVier** [comment]
@lucca65 the claim card might be too small for that. If we add just the image, it doesn't feel clear enough what happened:
2021-06-07-162958_317x277_scrot

And if we add some text explaining it, it's not going to fit or it's not going to be visible :grimacing:

**Comment by lucca65** [comment]
@rafachadud @juramos-2020 any ideas? PDF can sometimes be un-loadable, so we need some kind of glyph to inform the user the loading failed

**Comment by juramos-2020** [comment]
hi @lucca65  I'll talk to @rafachadud  tomorrow about this.

**Comment by NeoVier** [comment]
Ping @juramos-2020 @rafachadud

**Comment by juramos-2020** [comment]
Hi @NeoVier 

@rafachadud  is developing something about this requests

**Comment by rafachadud** [comment]
Hi @NeoVier, I prepared this card for showing that it is a PDF file that can not load on the preview. 

https://www.figma.com/file/N2lbB9xdO6tFbfg2Is4h7s/claim_with_image?node-id=1500%3A50

**Comment by NeoVier** [comment]
Awesome @rafachadud thank you! :pray: :fire:

**Review by lucca65 — APPROVED** [review]

**Comment by NeoVier** [comment]
@juramos-2020 can you give this a test?

Not sure if you've ever done this, so here's some instructions in case you need them (if you already know what to do, you can ignore this :sweat_smile:):

To access the app on this version, you can look on the box that says "All checks have passed", look for the row that says "deploy/netlify - Deploy Preview ready!" and click on "Details". That will bring you to the app on this version (you need an account from staging to log in). Once you're in the app, you can follow the test instructions that are on the top of this page (where it says "How to test").

When you're done with the testing, you can just comment here or approve this pull request (there should be a box at the very top of this page that says I requested your review, and you can add your review - either requesting changes, approving it or just commenting on it)

 Let me know if you need any help!

**Comment by juramos-2020** [comment]
Hi @NeoVier 

I'm trying to access "details" but the page isn't loading.

image

**Comment by NeoVier** [comment]
@juramos-2020 that's weird, not sure what it's about :thinking:. Anyway, in the meantime, I deployed this version to staging, so you can test it on [the staging server](https://cambiatus.staging.cambiatus.io)

**Comment by juramos-2020** [comment]
Hi @NeoVier 

Help me plis! rsrs

I accessed this link: https://cambiatus.staging.cambiatus.io/

For me to make a Claim, there should be no "Action" option in "goals and actions" , right?
No action is showing for me.

WhatsApp Image 2021-06-10 at 16 18 35

**Comment by juramos-2020** [comment]
Hi @NeoVier Here is of the testes:

- Try to claim an action that requires photo proof -  **It is working**
- See if you can choose to upload a pdf as well as an image - **It is working**
- Try uploading an image and see if it still works (should be uploaded and shown on the preview) -  **JPG it's working. I tried up to 5M and it worked**

- Try uploading a .pdf file and see if it works as well (should be uploaded and shown on the preview):

**pdf with 728 kb working**
**pdf with 1,07 MB working**
**pdf with 2,19 mb did not working**

PDF 2MB


**when I clicked "back" (on the arrow on the top bar) after confirming the claim, I was taken to the "edit community" screen**

Seta de voltar


- Go to your claims and see if you can see a preview of the pdf file on the claim card - **It is working**


- Open the claim and see if you can see a preview of the pdf on the claim page/modal - **It is working**


\o/

**Comment by NeoVier** [comment]
Thanks for the detailed tests @juramos-2020! :fire: 

That back button issue is weird, I'll take a look at it in another issue :thinking:

**Pull request merged**
