### PR TITLE
Feature/delete kyc 315

### LINKED ISSUE #315: Allow users to delete their KYC information from the profile 10
Should be finished after cambiatus/backend/issues/58 is finished.

### PR DESCRIPTION
**Pull request by amiskov**
## What issue does this PR close
Closes #315 

## Changes Proposed (a list of new changes introduced by this PR)
Use mutation for deleting KYC from the User Profile.

The button on the [original design](https://www.figma.com/file/47BEsGEMSWfhTm3zC0ugyA/Ticolones-version?node-id=948%3A468) has a "Disallow" label, but we [agreed](https://cambiatus.slack.com/archives/CA83HJAAD/p1599143391104000?thread_ts=1599142292.100500&cid=CA83HJAAD) that "Delete" would be more appropriate since this data will be completely removed from the DB.

## How to test (a list of instructions on how to test this PR)
- Make sure you have KYC data filled for your user.
- Go to the Profile page and press the "Delete" button from the "KYC Data" item.
- The KYC data should be deleted from the DB, the page should not have KYC fields.

### CODE REVIEW

**Comment by amiskov** [comment]
Now, to delete the KYC and the Address I used [2 separate mutations](https://github.com/cambiatus/frontend/pull/351/files#diff-f7eec667bfac7d2622ae36e82c105b4eR679-R711) on the frontend. But GraphQl allows having one mutation for the same thing. In pure GraphQl it looks like this:

```graphql
mutation ($input: KycDeletionInput!) {
  deleteKyc(input: $input) {
    status
    reason
  }
  deleteAddress(input: $input) {
    status
    reason
  }
}
```

@cambiatus/developers maybe you have some hints on how to achieve this on the Elm side with `elm-graphql`? I tried to compose types by hand for that, but it's was like 🤯 for me... We also have [the same approach](https://github.com/cambiatus/frontend/pull/341/files#diff-e8bb61f1016a235ea786c4c567db0c11R816-R833) on the Registration page with saving KYC and the Address.

**Comment by lucca65** [comment]
hm, I never though of doing this to be honest, I looked around the library and found [this](https://github.com/dillonkearns/elm-graphql/issues/389) issue, that has an example on how to do this (with query) but I guess it will work exactly the same

**Comment by amiskov** [comment]
The build is temporary broken due to renaming the repo name for one of the packages we use: `Skinney/murmur3` → `robinheghan/murmur3`.

**Comment by amiskov** [comment]
> hm, I never though of doing this to be honest, I looked around the library and found [this](https://github.com/dillonkearns/elm-graphql/issues/389) issue, that has an example on how to do this (with query) but I guess it will work exactly the same

@lucca65 It works! Thanks for pointing me to this thread :) I used this approach for [deleting both KYC data and Address in one mutation](https://github.com/cambiatus/frontend/pull/351/files#diff-e9cf2bf92b94f50af72059d0559a5a32R279-R289).

**Review by lucca65 — APPROVED** [review]

**Comment by lucca65** [comment]
@amiskov turns out to be quite simple, although its not very obvious that its a selection select, guess the naming is generic when in graphql playground we don't use that word (SelectionSet)

**Comment by lucca65** [comment]
I'll go ahead and merge this

**Pull request merged**
