### PR TITLE
Fix/cursor

### LINKED ISSUE #521: We don't store cursorId on the query string params on the analysis page
**Describe the bug**
When exploring the `/dashboard/analysis` page we don't keep the filters and cursors, so when we click on a specific page and try to go back where we left off, we need to explore again, clicking the "more button" and/or selecting filters again

**To Reproduce**
1. Go to `/dashboard/analysis` page
2. Click on "Show next 16 items"
3. Click on any claim
4. Try to go back
5. see error

**Expected behavior**
We should see where we left off

### PR DESCRIPTION
**Pull request by victorgdev**
## What issue does this PR close
Closes #521 

## Changes Proposed ( a list of new changes introduced by this PR)
Give the user the ability to navigate into specific filtered claims' pages, and when using the back button, have the previous filtering result displayed. This implements storing `cursorId` and `pageInfo` to be able to save the previously Loaded list of claims to have a more intuitive and functional analysis exploring UX. 

- Saves the `cursorId` string
- Creates a `Show previous 16 Claims` button

## How to test ( a list of instructions on how to test this PR)
1. Go to /dashboard/analysis page
2. Click on "Show next 16 items"
3. Click on any claim
4. Try to go back
5. See the previous filtering state

### CODE REVIEW

**Comment by victorgdev** [comment]
@lucca65 can we talk about this sometime this week?

**Review by lucca65 — CHANGES_REQUESTED** [review]
It doesn't get back correctly bro. It happens a lot of weird things:

- the more button goes up
- if I go back with the browser, it doesn't work
- It messes itself up as I go in and out the details.


https://user-images.githubusercontent.com/1082127/117142925-a3c8c980-ad86-11eb-8281-7e1ee55e1bec.mov



Also GitHub noticed but you are missing formatting.

**Comment by victorgdev** [comment]
Yes. We are still working on this. The cursorId retrieved and stored via pageInfo is not being done correctly. Plus we are trying not to have a page reload when loading claims via "show more" buttons.

**Comment by lucca65** [comment]
@victorgdev this is already 14 days without activity, this is not good because with so much time without doing nothing with it we loose context.

**Comment by victorgdev** [comment]
> @victorgdev this is already 14 days without activity, this is not good because with so much time without doing nothing with it we loose context.

Me and @Henrique decided to pause this improvement due its low-impact and because of the multi-domain implementation and finishing up of the neutro app mvp, which was completed today.

In terms of update for this issue, the last one was to give up the cursor Id approach and have claim search and filtering being a modal, which per our conversation was already designed by Helton.

**Comment by lucca65** [comment]
when why not simply close it? PRs are cheap bro ;)

if the code is longer useful than more reason to end it ☠️

**Comment by victorgdev** [comment]
Improvement no longer needed via this solution approach. Here is the substitute issue #536  for the enhancement.

**Comment by lucca65** [comment]
i've also changed @NeoVier handle on your comment because you commented about another person we don't know 😂

**Pull request closed without merging**
