### PR TITLE
Feature/terms of service

### LINKED ISSUE #661: Add link to terms of service
**Is your feature request related to a problem? Please describe.**
Users should consent to our terms of service

**Describe the solution you'd like**
Add a link to our terms of service on the app

**Describe alternatives you've considered**
Add a link to the footer, as proposed by @juramos-2020 on slack: https://www.figma.com/file/pjrI6ovITeudHw8CYYY7HV/Terms-%26-Conditions-%7C-Cookie-%26-LGPD?node-id=110%3A821

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by NeoVier**
## What issue does this PR close
Closes #661 

## Changes Proposed ( a list of new changes introduced by this PR)
- Use the new `latestAcceptedTerms` field from GraphQL
- If that field is present, app works as normal
- Otherwise:
  - A modal will show to the user every time they reload, asking them to accept the terms of service
  - A bunch of buttons throughout the app will be disabled (transfer, invite, claim, buy...)
  - A card will show in some places, informing the user what's happening

## How to test ( a list of instructions on how to test this PR)
- Log into the app
- The first time, you should see the modal. Decline it (you need to decline it twice, and on the second time there is a delay, to make sure users read it)
- Go through the app. See if everything that shouldn't be doable by users who haven't accepted the terms are in fact not doable.
- Go to the dashboard, and accept the terms
- Go through the app again. Everything should work as usual
- Refresh the page. You shouldn't see the modal again, and the app should keep working as usual

### CODE REVIEW

**Comment by lucca65** [comment]
@NeoVier great work this looks amazing! Way better than I thought it would be to be honest, more clear, well thought and well presented. I love how the user can accept the terms at anytime. Also, when entering pages manually on the URL the app keeps locket! Amazing!

I only have one suggestion. We could have a horizontal display off the locked card to be shown in the community page and the shop. Maybe we can use a different vibrant color to make sure its super visible
Captura de Tela 2022-03-07 às 12 00 53

**Comment by NeoVier** [comment]
Yeah, I was thinking about having a horizontal view of the card as well, I think it looks kind of off on larger screens on the Shop and My Claims pages. I'll look into it!

**Comment by NeoVier** [comment]
@lucca65 I just updated it so it shows up with the image on the left on the Shop and Claims pages (on large enough screens), and I think it looks much much better! Can you take a look at it again?

image

Since it shows up at the top of the page, I don't think we need to use vibrant colors for it to be visible, and this white background with shadow approach matches what we've been going with on the rest of the app

**Review by lucca65 — APPROVED** [review]
🕺🏻 nice!

**Pull request merged**
