### PR TITLE
   Fix: autocomplete text

### LINKED ISSUE #76: Over imposed text
**Describe the bug**
Over imposed text when searching for a user to do a transfer. [iphone]
Over imposed numbers in PIN [Dell Computer]

**Expected behavior**
over imposed text

**Screenshots**
WhatsApp Image 2019-11-14 at 16 48 26

WhatsApp Image 2019-11-14 at 17 00 02

**Cambiatus Env you are using**
borboins.cambiatus.io

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: 
 - Browser  Safari
 - Version

### PR DESCRIPTION
**Pull request by zacck**
## Changes Proposed 

Fixes #76 

- [x] Adjust user autocomplete styles to prevent corruption when displaying 

## Screens  
Screenshot 2019-11-26 at 09 13 08

### CODE REVIEW

**Comment by lucca65** [comment]
also the tailwind configurations aren’t something i like. the ideia for the configurations is to have our style over helton’s design. it has to be consistent. having super exact values such as px don’t look good. old screens should live in the legacy_main.css and new design screens on tailwind

**Comment by zacck** [comment]
@lucca65  so would you rather I use the old css files and just modify those? Then when a new design  for auto complete items comes along we can refactor to tailwind?

**Comment by lucca65** [comment]
yeah! that is what i was thinking, so we don’t mess up tailwind with old stuff! makes sense?

**Comment by zacck** [comment]
@lucca65  I like that plan!

**Comment by zacck** [comment]
lol @lucca65  your suggestion ended up working much better!!!!

Screenshot 2019-11-27 at 07 56 28

**Comment by lucca65** [comment]
@zacck before merging can you change your user name to something big with 256 chars? that's the max allowed and it should work fine with long surnames

**Comment by zacck** [comment]
@lucca65  cool let me do that

**Comment by zacck** [comment]
@lucca65  here is how it looks now 
Screenshot 2019-11-28 at 07 34 30

**Pull request merged**
