### PR TITLE
Enhancement/Phone numbers

### LINKED ISSUE #508: Support more phone numbers
**Is your feature request related to a problem? Please describe.**
With new communities and users coming into the platform, we need to support phone numbers from more countries

**Describe the solution you'd like**
Support phone numbers from the following countries:
- [x] Portugal
- [x] Canada
- [x] United Kingdom
- [x] New Zealand

**Describe alternatives you've considered**
- Support specific countries (what we're doing now) with custom placeholders and icons
- Support all countries. We'd still have placeholders, but not well formatted (`11912345678` vs `11 91234 5678`), and would probably need to use a third-party icon set for the flags

**Additional context**
Came from [this slack thread](https://cambiatus.slack.com/archives/CA83HJAAD/p1619743728000300)

### LINKED ISSUE #510: Its not possible to delete contact information
**Is your feature request related to a problem? Please describe.**
There is no button to delete contact information, even with the API supporting it

**Describe the solution you'd like**
A delete/thrash button somewhere.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by NeoVier**
## What issue does this PR close
Closes #508, closes #510

## Changes Proposed ( a list of new changes introduced by this PR)
- Support new phone numbers:
  - [x] Portugal
  - [x] Canada
  - [x] United Kingdom
  - [x] New Zealand
- Add a better way to add new countries - just add them to `supportedCountries` in `Profile/Contact.elm`!
- Add "delete contact" button
- Let user delete contacts by just submitting empty ones in the profile edit contact page

## How to test ( a list of instructions on how to test this PR)

Test the contact modal:
1. Log in to an account that doesn't have any contact information
2. Go to the dashboard
3. See the contact modal
4. Check if the country selector (when you select either "Phone" or "Whatsapp") behaves as expected and has all the countries

Test the profile page:
1. Go to your profile
2. Go to the contact edit page
3. Check if the country selector behaves as expected and has all the countries
4. Try deleting contacts with the contact button and by leaving them blank

### CODE REVIEW

**Review by lucca65 — CHANGES_REQUESTED** [review]
it took me a second to realize that I have to hit save after deleting and confirming, why don't we simply delete it after the confirmation modal?

**Comment by NeoVier** [comment]
> it took me a second to realize that I have to hit save after deleting and confirming, why don't we simply delete it after the confirmation modal?

+1, that really is confusing. I'm fixing this

> Also the dropdown only shows 4, I think its safe to show everything, at least keep the min height is the limit to the bottom o f the screen

IMO it looks too long if we show the entire thing (and will become longer and longer with new supported countries):
2021-05-04-130511_1308x433_scrot

And it kind of breaks the modal:
2021-05-04-130632_882x723_scrot

**Comment by lucca65** [comment]
i see, my suggestion would be a bad solution then... what do you think about adding a transparent 50% white bg with a down arrow? showing that there is more below?

**Comment by NeoVier** [comment]
Is the browser scroll bar not enough? :thinking:

**Comment by NeoVier** [comment]
I just realized it fits **exactly** 4 countries, maybe we can change the height a bit, so it kind of crops another country? That would show there's more below

**Comment by lucca65** [comment]
lots of browsers nowadays don't show scrolls bars like old windows versions where they are always visible and in this case must take 20~30% of the space the flags take, instead its a bar that appears on top and is only visible while scrolling

**Comment by NeoVier** [comment]
> I just realized it fits exactly 4 countries, maybe we can change the height a bit, so it kind of crops another country? That would show there's more below

That's what that would look like:
2021-05-04-165541_1039x298_scrot

What do you think?

**Comment by lucca65** [comment]
not beautiful but for sure solves the problem

**Comment by lucca65** [comment]
When I have no contact it doesn't show the contact modal, did we reach that date limit?

**Comment by lucca65** [comment]
adding and then removing telegram made the modal appear 🤔

**Review by lucca65 — APPROVED** [review]

**Comment by NeoVier** [comment]
That might have been from a bug I had introduced earlier, but is now fixed. It made it so when you submitted empty contacts it would submit something like `https://t.me/`

**Pull request merged**
