### PR TITLE
Fix/long claim display

### PR DESCRIPTION
**Pull request by lucca65**
## What issue does this PR close
N/A

## Changes Proposed ( a list of new changes introduced by this PR)
- Truncate text if its too long on the view claim
- Overflow hidden on long claim text on voting cards (/dashboard)
- Also changed the symbol display on the feedback message, it was including the symbol precision

## How to test ( a list of instructions on how to test this PR)
- Create an action with a very long description, but make sure it have long words (like one of those microsoft URLs, boy they sure love incredibly hard to share URLs)
- Claim it and make sure you are one of the validators
- See the error

### CODE REVIEW

**Comment by lucca65** [comment]
also, the new Tailwind documentation is AWESOME

**Review by amiskov — DISMISSED** [review]
The Dashboard looks good! I also noticed that there's a small issue on the Claim View page with those long words:
image

Maybe this PR is a good place to tweak the left margin for the header on the Claim View page as well?

**Comment by lucca65** [comment]
+1! Added the fix for this case as well! thanks for noticing that @amiskov

**Review by amiskov — APPROVED** [review]
👍

**Pull request merged**
