### PR TITLE
Use the GraphQL shop API

### LINKED ISSUE #730: Update Shop integration to stop using blockchain
**What we have**
We currently use EOSIO to store our offers, synced up with our Postgres database by event source. Although

**Proposal**
Start using our new GraphQL Shop mutations to create products

**Why**
Although this is working, its hard for us to do any changes or big improvements to the flow, such as orders, tracking, categories etc. 

**How**
Follow the changes introduced on https://github.com/cambiatus/backend/pull/220 to keep the same functionality as we have today. 

There are a few minor changes: 
- We now allow for multiple images
- We now send back validation errors. Frontend should check and handle those

**Additional context**
This is the first step on rebuilding our shop with new features

### PR DESCRIPTION
**Pull request by NeoVier**
## What issue does this PR close
Closes #730 

## Changes Proposed ( a list of new changes introduced by this PR)
- [x] Use the new shop GraphQL API to create products
- [x] Use the new shop GraphQL API to update products 
- [x] Use the new shop GraphQL API to delete products
- [x] Redirect to the created/updated product after saving it (instead of redirecting to the shop listing)

## How to test ( a list of instructions on how to test this PR)
Try to create and update products!

### CODE REVIEW

**Comment by NeoVier** [comment]
I just tried to buy a product that tracks stock, and I got an error that says "assertion failure with message: Sale doesn't have that many units available", even if I bought an allowed amount

Products that don't track stock are working fine

**Comment by NeoVier** [comment]
I guess that error was because I edited that sale through graphQL and the blockchain doesn't know about it? I just tried on one that already had unit tracking (before the graphQL api) and it worked fine

**Comment by lucca65** [comment]
yeah, that's it. Since we are saving on Postgres, the blockchain doesn't know about this anymore. I've published a new version of our contract on staging without these verifications. It should allow you to buy normally

**Comment by NeoVier** [comment]
Yep, I can buy it! 💪

**Review by lucca65 — APPROVED** [review]
😌

**Pull request merged**
