### PR TITLE
Refactor feedback messages to comply with new system

### PR DESCRIPTION
**Pull request by RodrigoLeiteF**
## Changes Proposed ( a list of new changes introduced by this PR)
Adds positive feedback for the following actions
1. Editing a profile
2. Creating and editing an objective
3. Creating and editing an action
4. Creating, editing and deleting an order

## How to test ( a list of instructions on how to test this PR)
Open the relevant pages and complete the described actions. A feedback
should appear at the top.

### CODE REVIEW

**Comment by lucca65** [comment]
Also what are your thoughts on changing the type for Show message?

instead of using a record  with `ShowFeedback { message : String, success : Bool }` why not `ShowFeedback String Bool`? I think its simple enough to justify the change. 

What do you think @RodrigoLeiteF?

I would love to know @amiskov thoughts on this too

**Comment by RodrigoLeiteF** [comment]
> Also what are your thoughts on changing the type for Show message?
> 
> instead of using a record with `ShowFeedback { message : String, success : Bool }` why not `ShowFeedback String Bool`? I think its simple enough to justify the change.
> 
> What do you think @RodrigoLeiteF?
> 
> I would love to know @amiskov thoughts on this too

I personally prefer using a record with named parameters. Ime it's almost always hard to infer what an unnamed boolean does. For example, reading `ShowFeedback "Action created successfully" True` or `ShowFeedback "Internal server error" False` isn't very intuitive I think.

**Comment by amiskov** [comment]
> instead of using a record with `ShowFeedback { message : String, success : Bool }` why not `ShowFeedback String Bool`?

Looks like a simple functions to me: `showSuccess "Successfully done!"`, `showFailure "Error..."`. But if it has to be a type, then I agree with @RodrigoLeiteF: explicit is better than implicit :)

**Comment by RodrigoLeiteF** [comment]
After some discussion with friends I think it would be best to use a type for `Success | Failure` instead, which would result in `ShowFeedback "Successfully claimed action" Success`. We use a similar pattern for the feedback status on LoggedIn.elm (custom type as opposed to Maybe) :)

**Comment by lucca65** [comment]
+1 in the `ShowFeedback Status String` approach (maybe its best to leave the message as the second param)

**Comment by lucca65** [comment]
Looks good @RodrigoLeiteF, you'll need to deploy it so Helton can test it out

**Pull request merged**
