### PR TITLE
Translation and symbol display fixes

### PR DESCRIPTION
**Pull request by lucca65**
Fix symbols display and a translation that was in Portuguese when in Spanish

### CODE REVIEW

**Review by amiskov — DISMISSED** [review]
Nice!

**Comment by lucca65** [comment]
Sorry @amiskov a new wild fix emerged during the presentation 😬 , can you review it again please?

**Review by amiskov — APPROVED** [review]
Looks good :)

**Comment by lucca65** [comment]
Happened again, though I would be faster than you @amiskov 😢

**Review by amiskov — APPROVED** [review]
Approved!

**Pull request merged**
