### PR TITLE
Feature/show profile contacts

### LINKED ISSUE #472: Adds contact information to the public profile
We need to make sure that we only display if the loggedIn user belongs to any of the public profile user communities.

Also extend this logic to KYC information that is displayed on the public profile too.

https://www.figma.com/file/ILiFX32kN5TRQtUhbA0Z5u/New-Shop?node-id=13%3A4356

### LINKED ISSUE #474: Update contact information on the Private Profile

### PR DESCRIPTION
**Pull request by NeoVier**
## What issue does this PR close
Closes #472 and closes #474 

## Changes Proposed ( a list of new changes introduced by this PR)
- Update profile styles (https://www.figma.com/file/ILiFX32kN5TRQtUhbA0Z5u/New-Shop-Contact?node-id=0%3A1)
- Show contact information on the public profile
- Add possibility to add/edit own contacts (Instagram, Phone, Whatsapp, Telegram)

## How to test ( a list of instructions on how to test this PR)
- Private profile:
    - Log into your account, and go to your profile
    - Try adding contact information
    - Try adding contact information again and see if the previous changes have persisted
    - Go to the public view of your profile and test as described below
- Public profile:
    - Go to someone else's profile
    - See the contact buttons
    - Test the contact buttons to see if they redirect you to the correct app/site

### CODE REVIEW

**Comment by NeoVier** [comment]
@lucca65 @amiskov sorry for the long list of commits :grimacing: they're mostly from #485 and #479. This PR starts at the `Add Profile.AddContact` (a020d32) commit

**Comment by lucca65** [comment]
@NeoVier can you change the target branch for this PR? It would be best for us to have a feature branch (in this case `feature/contact` or something similar) and merge the parts of it until we have a complete whole to merge to master. The problem with the approach you've taken is that its not only hard to review, but you have to keep maintaining both PRs updated with master (#479 isn't as the time of this writing). We haven't formalized this in our docs but its a good hint nonetheless.

Also please keep in mind that you are responsible for seeing the merged, looks like in this case this PR is stale because of the lack of reviews, so make sure you ping us if you notice that. We don't bite (a lot)!

It's important to keep this in mind because long PRs make us loose context and in general makes testing and fixing more painful than they already are!

**Comment by NeoVier** [comment]
Yeah, I realize this is pretty hard to review, my bad.

I'm not sure I understand what you mean. Should I create a `feature/contact` branch, merge this and #479 to it, so you guys can review that new branch, and eventually merge that to master?

I can also recreate the actual changes from this PR in the new branch if that's easier to review

**Review by lucca65 — CHANGES_REQUESTED** [review]
we need to add the width of the main container in the right side

**Pull request merged**
