### PR TITLE
Enhancement/community in context

### LINKED ISSUE #782: Update queries that need community id
**What we have**
We have a lot of queries that need the current community symbol to work.

**Proposal**
Update those queries so that we don't need to give them the symbol anymore

**Why**
On https://github.com/cambiatus/backend/pull/252, we don't need this argument anymore

**How**
Run `yarn generate-graphql` and solve the errors

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by NeoVier**
## What issue does this PR close
Closes #782 

## Changes Proposed ( a list of new changes introduced by this PR)
- Update graphql schema and follow the errors to make the app compile

## How to test ( a list of instructions on how to test this PR)
Test the mutations and queries to make sure everything works. Here's an exhaustive list of the queries and mutations affected:

- Updating community contacts (`community` mutation)
- Updating community `hasNews` (`community` mutation)
- Set highlighted news (`highlightedNews` mutation)
- Editing news (`news` mutation)
- Contributing to the community (`contribution` mutation)
- Fetching pending claims (`pendingClaims` query)
- Fetch claims on analysis page (`pendingClaims` and `analyzedClaims` queries)
- Fetching products (`products` query)
- Creating and editing products (`product` mutation)
- Searching for things (`search` query)
- Subscribing to highlighted news (`highlightedNews` subscription)

### CODE REVIEW

**Review by lucca65 — APPROVED** [review]
aquela issue de deixar o trabalho duro pro compilador do Elm 🫶

**Comment by NeoVier** [comment]
@MatheusBuss podemos mergear esse PR ou tem algo faltando no https://github.com/cambiatus/backend/pull/252?

**Comment by MatheusBuss** [comment]
Acho que seria legal testar se o erro do Sentry ficou mais útil agora

**Comment by NeoVier** [comment]
Eu e o @MatheusBuss conversamos pelo Slack e já podemos mergear 👍

**Pull request merged**
