### PR TITLE
Feature/archive objective

### LINKED ISSUE #168: The buttons on actions and objectives must be disable when marked as complete
## Description
Add archive objective button. 

Archived objectives must not allow actions to be edited, making the edit button disabled.

This form is only visible on an admin page:

1. Create a new community on the path `/community/new`, after its done, reload the app
2. After its created, click the cog on the top right part of the page (make sure you've selected the new community on the selector, top left of the screen)
3. Go to Objectives and actions, place where you can create objectives and their actions
4. Create test objectives and actions
5. Implement the archive button

## How to implement

We have a GraphQL mutation to implement this, please use staging GraphQL interface: https://staging.cambiatus.io/api/graphiql

```graphql
mutation {
  completeObjective(input: {objectiveId: 1}) {
    isCompleted
    community {name}
  }
}
```

After the archiving is done, we need to properly disable the buttons, and follow the updated designs, that can be seem below

## Designs
The buttons on actions and objectives must be disable when marked as complete, so that users can not edit (image below)

Screen Shot 2020-02-17 at 15 54 56

ON HTML (Even complete the button is enabled):
Screen Shot 2020-02-17 at 15 57 30

**Cambiatus Env you are using**
app.cambiatus.io

### PR DESCRIPTION
**Pull request by NeoVier**
## What issue does this PR close
Closes #168 

## Changes Proposed ( a list of new changes introduced by this PR)
- Add a "Mark as Completed" button in the ObjectiveEditor page (`community/:symbol/objectives/:objective_id/edit`)
- Add a tag if the objective is completed in the Objectives page (`community/:symbol/objectives`) and disable the "Edit Objective" and "Create Action" buttons, as well as all of the "Edit Action" buttons

## How to test ( a list of instructions on how to test this PR)
1. Select a community you're the admin of
2. On the Dashboard, click on the Cog icon (top right corner)
3. If the community doesn't have any objectives, create one
4. No objective should have the "Complete" tag
5. Click on an objective, and click "Edit objective"
6. On the "Edit Objective" page, click "Mark as Completed"
7. Be redirected back to the "Objectives" page
8. See the objective you marked as complete now has a "Complete" tag
9. Click the objective you marked as complete and see all of the buttons mentioned above as disabled and non-clickable

### CODE REVIEW

**Comment by NeoVier** [comment]
@lucca65 I see the `Action` object also has a `isCompleted` field, but I don't see any `completeAction` mutation :thinking: should there be one?

**Comment by lucca65** [comment]
no, actions can only be completed by:
1. opening claims and by voting on them until all usages are done
2. closing it via edit, using the `upsertaction` smart contract action

**Review by lucca65 — DISMISSED** [review]
🧹💨

**Comment by NeoVier** [comment]
@heltonlr can you test this out? It should be very quick, and I fixed the netlify deploy, so you can use that! (I haven't deployed this to staging, so please use netlify deploy above :sweat_smile: )

**Comment by heltonlr** [comment]
Hey @NeoVier, everything working well.

Only, please insert a confirmation modal after the user clicks on "Mark as complete" (a good example is the delete modal). 

And a question only to confirm. Actions that have been already claimed before the admin clicks on "Mark as complete" button (objective), are still open to be analyzed, correct?

---

Em português:

_Açõe de um Objetivo que foram reivindicadas antes de Objetivo ser marcado como completo ainda permanecerão disponíveis para análise_

**Comment by heltonlr** [comment]
> Hey @NeoVier, everything working well.
> 
> Only, please insert a confirmation modal after the user clicks on "Mark as complete" (a good example is the delete modal).
> 
> And a question only to confirm. Actions that have been already claimed before the admin clicks on "Mark as complete" button (objective), are still open to be analyzed, correct?
> 
> Em português:
> 
> _Açõe de um Objetivo que foram reivindicadas antes de Objetivo ser marcado como completo ainda permanecerão disponíveis para análise_

You can find that confirmation modal trying to delete the KYC data...

**Comment by NeoVier** [comment]
> And a question only to confirm. Actions that have been already claimed before the admin clicks on "Mark as complete" button (objective), are still open to be analyzed, correct?

@heltonlr  No, actions marked as complete cannot be reviewed anymore (although the UI wasn't reflecting that in some areas, I'll fix that)

I'll add the confirmation modal as well.

**Comment by NeoVier** [comment]
@lucca65 When an admin marks an objective as completed, should all the actions under that objective also be marked as completed?

**Comment by heltonlr** [comment]
I mean, the actions that were claimed before they were marked as complete (or your objective to be marked as complete). In this case, in the interface currently, these actions continue to appear to be voted by the admins and I think that is ok to occur, as they were claimed before.

what do you think about @NeoVier and @lucca65 ?

**Comment by NeoVier** [comment]
Yeah, on the card view, even if the action is completed, you can vote on it (that's what I'm fixing - to just show the "More details" button). But if you actually click the card to see more details, it says "This claim is pending, however, since the action is completed, it's not possible to vote", and if you try to vote on it, you'll get an error

**Comment by heltonlr** [comment]
> Yeah, on the card view, even if the action is completed, you can vote on it (that's what I'm fixing - to just show the "More details" button). But if you actually click the card to see more details, it says "This claim is pending, however, since the action is completed, it's not possible to vote", and if you try to vote on it, you'll get an error

In that case, we need to be more clear with the users. I can open an improvement for that.

**Comment by NeoVier** [comment]
> In that case, we need to be more clear with the users. I can open an improvement for that.

Do you mean showing the votes button even if the action is completed? If so, I just fixed that!

**Comment by lucca65** [comment]
I'm waiting for @heltonlr reply before reviewing

**Comment by NeoVier** [comment]
@heltonlr talked to me on Slack, and it was that, so it's all fixed!

> When an admin marks an objective as completed, should all the actions under that objective also be marked as completed?

What about this though?

**Comment by lucca65** [comment]
hmm, slack is goof folks but let's try to at least reflect the final decision on github, as this is the place where we can refer to (good luck finding anything on slack)

about the question, i think it should create several transactions to complete child actions

**Comment by lucca65** [comment]
we will probably need a "tool" for that, like a modal with a progress bar, sometimes transactions fail for a number of reasons

**Comment by heltonlr** [comment]
Hey everyone. So, for me, the task is approved. The actions inside an objective that was marked as completed, will show only the button "more details" for now. I going to add on Rice's table an improvement to show a different status tag for that cases where the action is "pending" to validate.

**Comment by lucca65** [comment]
@heltonlr I've already implemented that case. this conversation is running in cycles

**Comment by NeoVier** [comment]
> we will probably need a "tool" for that, like a modal with a progress bar, sometimes transactions fail for a number of reasons

I guess this might take longer than expected then. Should I leave this on hold for now and come back to it after the subdomain PR?

**Comment by lucca65** [comment]
it can be another issue, but i think we need to revert the change you made that allow claims to be voted after the action was closed

**Comment by NeoVier** [comment]
> the change you made that allow claims to be voted after the action was closed

I only changed the view, actually.

There are two views for the claim analysis: card view and full screen view. The card view is the one on the dashboard and on the analysis page (`/dashboard/analysis`). The full screen view is the one on the specific action review screen (`/objectives/:objectiveId/action/:actionId/claim/:claimId`).

If the action is marked as complete, the full screen view showed the "This claim is pending, however, since the action is completed, it's not possible to vote" message, but the card view showed the vote buttons (Disapprove/Approve).

What I did was change the card view to just show the "More details" button instead (if the action is marked as complete)

**Comment by NeoVier** [comment]
Right now, if a user makes a claim and the community admin marks that objective as completed, that claim can still be reviewed, because the action is not marked as complete

**Comment by NeoVier** [comment]
@lucca65 is there something else to do on this, considering we'll handle marking actions as completed when we mark objectives as completed on another issue? :thinking:

**Comment by lucca65** [comment]
I guess just opening the issue. I'll review the feature once again.

**Pull request merged**
