### PR TITLE
Fix/accented 12 words

### PR DESCRIPTION
**Pull request by henriquecbuss**
## What issue does this PR close
Closes N/A. Issue reported by @muguika on Slack: https://cambiatus.slack.com/archives/CA83HJAAD/p1668889849511849

## Changes Proposed ( a list of new changes introduced by this PR)
- Normalize all bip39 wordlists
- Upgrade elm-review packages and run `elm-review --fix-all` (this introduced a lot of line changes, but it was fully automated. The main change for this PR is in `index.js`)

## How to test ( a list of instructions on how to test this PR)
- Create an account with the app in spanish
- Make sure there is at least one accented word in the 12 words
- Try to log in (try copy-pasting and manually writing the accented word)

### CODE REVIEW

**Comment by henriquecbuss** [comment]
@lucca65 seems like we're using a really old Linux to build the netlify previews 😅 

image

Can you [change it in the settings](https://app.netlify.com/sites/cambiatus/settings/deploys#build-image-selection)? I don't have permission for it.

**Review by lucca65 — APPROVED** [review]
looks good! 👍

**Comment by muguika** [comment]
Fantastic! Let me know when I can test it

**Comment by henriquecbuss** [comment]
@muguika it's not on production yet, but you can test it on staging. For example, you can create an account in this community: [https://buss.staging.cambiatus.io](https://buss.staging.cambiatus.io) and see if everything works fine 🙂

**Comment by lucca65** [comment]
done! ✅

**Comment by muguika** [comment]
Tried it but still got the same issue

**Comment by muguika** [comment]
Wouldn't be better to transform all accented words to not accented? Accents are always an issue

**Comment by henriquecbuss** [comment]
That's likely a browser cache issue. Can you try refreshing the page or opening it in an anonymous tab?

> Wouldn't be better to transform all accented words to not accented? Accents are always an issue

I don't think it makes sense to get rid of the accents. The list of words is actually a standard (called [bip39](https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md)), and we probably don't want to use our own standard

**Pull request merged**
